apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: conjurs.conjur.cyberark.com
spec:
  group: conjur.cyberark.com
  names:
    kind: Conjur
    listKind: ConjurList
    plural: conjurs
    singular: conjur
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
